export const IMAGES = {
  appleLogin: require("../assets/images/btn_apple_login.png"),
  kakaoLogin: require("../assets/images/btn_kakao_login.png"),
  headerBack: require("../assets/images/btn_header_back.png"),
  headerCart: require("../assets/images/btn_header_cart.png"),
  headerClose: require("../assets/images/btn_header_close.png"),
  headerHome: require("../assets/images/btn_header_home.png"),
  homeCart: require("../assets/images/btn_home_cart.png"),
  berryGrey: require("../assets/images/ic_berry_grey.png"),
  berry: require("../assets/images/ic_berry.png"),
  logoWhite: require("../assets/images/ic_logo_white.png"),
  logo: require("../assets/images/ic_logo.png"),
  navHome: require("../assets/images/ic_nav_home.png"),
  navMembership: require("../assets/images/ic_nav_membership.png"),
  navMypage: require("../assets/images/ic_nav_mypage.png"),
  navOrderDetails: require("../assets/images/ic_nav_order_details.png"),
  navSearch: require("../assets/images/ic_nav_search.png"),
  quantityMinus: require("../assets/images/ic_quantity_minus.png"),
  quantityMinusDisabled: require("../assets/images/ic_quantity_minus_disabled.png"),
  quantityPlus: require("../assets/images/ic_quantity_plus.png"),
};
