export const TEXT = {
  ice: "ICE",
  hot: "HOT",
  size: "기본",
  loginStart: "로그인하고 시작하기",
  orderNow: "바로 주문",
  mypage: "마이페이지",
  search: "카페검색",
  eventing: "진행 중인 이벤트",
  putInCart: "장바구니 담기",
  orderCaffee: "주문매장",
  orderLists: "주문내역",
  orderDetails: "주문상세",
  ordering: "주문하기",
  paying: "결제하기",
  eatShop: "먹고갈게요",
  packaging: "가져갈게요",
  check: "확인",
  orderRequest: "주문요청",
  orderConfirmation: "주문확인",
  completed: "제조완료",
  Pickup: "픽업완료",
};
